apps/youtube/urls.py
from django.urls import path
from . import views

app_name = 'youtube'

urlpatterns = [
    path('extracted/', views.extracted, name='extracted'),
    path('downloading/', views.downloader, name='downloader'),
    path('download/<str:path>/', views.download_file, name='download_file'),
]

core/urls.py
# -*- encoding: utf-8 -*-
"""
Copyright (c) 2019 - present AppSeed.us
"""

from django.contrib import admin
from django.urls import path, include  # add this

urlpatterns = [
    path('admin/', admin.site.urls),                # Django admin route
    path('weather/', include('apps.weather.urls', namespace='weather')),
    path('mp3-extractor/', include('apps.youtube.urls', namespace='youtube')),
    path('gcp/', include('apps.gcp.urls', namespace='gcp')),
    path('aws/', include('apps.aws.urls', namespace='aws')),
    path('', include('apps.authentication.urls')),  # Auth routes - login / register
    path('', include('apps.home.urls')),             # UI Kits Html files
]

apps/youtube/models.py
from django.db import models


class Song(models.Model):
    url = models.URLField()
    title = models.CharField(max_length=100)
    downloaded = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.title}"

apps/youtube/forms.py
from django import forms
from .models import Song


class SongForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['url'].widget.attrs.update({'class': 'form-control mb-4',
                                                'placeholder': 'Paste URL of the song here ...',
                                                'type': 'search',
                                                })
        self.fields['title'].widget.attrs.update({'class': 'form-control',
                                                  'placeholder': 'Give a name to your song, e.g. ABBA - Waterloo ...',
                                                  'type': 'text',
                                                  })

    class Meta:
        model = Song
        exclude = ['downloaded']
        fields = ['url', 'title']

apps/youtube/views.py
import glob
import mimetypes
import os

from django.conf import settings as project_settings
from django.contrib import messages
from django.core.paginator import EmptyPage, Paginator, PageNotAnInteger
from django.http import HttpResponse
from django.shortcuts import render, redirect

from .forms import SongForm
from .models import Song
from .tasks import yt_downloader


def extracted(request):
    song_list = []
    dir_path = project_settings.MEDIA_ROOT
    for full_path in glob.iglob(dir_path + '/youtube/' + '*.mp3'):
        print(f"{full_path=}")
        song_list.append([full_path, os.path.basename(full_path)])

    paginator = Paginator(song_list, 5)
    page = request.GET.get("page")
    try:
        songs = paginator.page(page)
    except PageNotAnInteger:
        songs = paginator.page(1)
    except EmptyPage:
        songs = paginator.page(paginator.num_pages)

    if request.method == "POST":
        form = SongForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            url = cd['url']
            if Song.objects.filter(url=url).exists():
                messages.warning(request, 'This file was already downloaded!')
                return redirect('youtube:extracted')
            else:
                form.save()
            yt_downloader.delay(url)  # launch asynchronous task
            return redirect('youtube:downloader')
    else:
        form = SongForm()
    return render(request, 'youtube/extracted-songs.html',
                  {'form': form,
                   'song_list': song_list,
                   'page': page,
                   'songs': songs})


def downloader(request):
    return render(request, 'youtube/downloading-song.html')


def download_file(request, path):
    folder_path = project_settings.MEDIA_ROOT + '/youtube'
    print(f"{folder_path=}")
    file_path = os.path.join(folder_path, path)
    if os.path.exists(file_path):
        with open(file_path, "rb") as fh:
            mime_type, _ = mimetypes.guess_type(file_path)
            response = HttpResponse(fh.read(), content_type=mime_type)
            response["Content-Disposition"] = "attachment; filename=" + os.path.basename(
                file_path
            )
            return response
        raise Http404("Nie ma takiego pliku!")
    else:
        return render(request, "youtube/404.html")

apps/templates/youtube/downloading-song.html
{% extends "layouts/base.html" %}

{% block title %} Extracted songs {% endblock %}

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}
    <main>
        <div class="col-12 col-xl-12">
            <div class="card text-center">
                <div class="card-header">
                    <h2 class="h5 mb-4">Your file is being downloaded ...</h2>
                    <i class="fas fa-download fa-6x"></i>
                </div>
            </div>
        </div>

        <div class="container py-4">
            <div class="p-5 mb-4 bg-light rounded-3">
                <div class="container-fluid py-5">
                    <h1 class="display-5 fw-bold mb-4">Is it legal?</h1>
                    <p class="col-md-12 fs-4">
                        Short answer: Yes. You aren’t allowed to download material that is copyrighted if you do not have express permission.
                        If the content is not copyright, then you are allowed to download or "rip" both the audio and video from YouTube uploads.
                    </p>
                    <p class="col-md-12 fs-4">
                        Ripping audio content from videos uploaded on YouTube breaks YouTube’s <a href="https://www.youtube.com/static?template=terms" target="_blank">terms of service</a> (TOS).
                        There’s a big difference between US copyright laws and YouTube’s TOS.
                        Violating YouTube’s terms of service is not illegal by law but YouTube could ban your account.
                    </p>
                    <p>You will be redirected to the page with your songs in <span id="timer">60 seconds</span> ...</p>
                    <a class="btn btn-primary btn-lg" href="{%  url 'youtube:extracted' %}" role="button">Go now!</a>
                </div>
            </div>
        </div>
    </main>


{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}
    <script>
    let count = 60
    let counter = setInterval(timer, 1000)

    function timer(){
       count = count-1
       if (count <= 0)
       {
           clearInterval(counter);
           window.location.href = "{% url 'youtube:extracted' %}"
       }
       document.getElementById("timer").innerHTML= count + " seconds";

}
    </script>
{% endblock javascripts %}

apps/templates/youtube/extracted-songs.html
{% extends "layouts/base.html" %}

{% load proper_paginate %}
{% load url_replace %}

{% block title %} Extracted songs {% endblock %}

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}
    <div class="row">
        <div class="col-12 col-xl-12">
            <div class="card card-body border-0 shadow mb-4">
                <h2 class="h5 mb-4">MP3 extractor</h2>
                <form action="{%  url 'youtube:extracted' %}" method="post">
                    {%  csrf_token %}
                    <div class="row">
                        <div class="col-md-12 mb-3">
                            <div>
                                {{ form.url }}
                                {{ form.title }}
                            </div>
                        </div>
                    </div>
                    <div class="mt-3">
                        <button class="btn btn-gray-800 mt-2 animate-up-2" id="download_btn" type="submit">Download </button>
                    </div>
                </form>
            </div>
        </div>
    </div>

    <div class="card card-body border-0 shadow table-wrapper table-responsive">
        <h2 class="h5 mb-4">Downloaded songs</h2>
        <table class="table table-hover">
      <thead>
          <tr>
              <th class="border-gray-200">#</th>
              <th class="border-gray-200">Title</th>
              <th class="border-gray-200">Preview</th>
              <th class="border-gray-200">Action</th>
          </tr>
      </thead>
      <tbody>
            {%  for song in songs %}
              <!-- Item -->
              <tr>
                  <td>
                      <a href="#" class="fw-bold">
                          {{ forloop.counter }}
                      </a>
                  </td>
                  <td>
                      <span class="fw-normal">{{ song.1 }}</span>
                  </td>
                  <td><span class="fw-normal">
                      <audio controls>
                          <source
                                  src="{% url 'youtube:download_file' song.1 %}"
                                  type="audio/mpeg">
                          Your browser does not support the audio element.
                      </audio>
                  </span>
                  </td>
                  <td>
                      <div class="btn-group">
                          <button class="btn btn-link text-dark dropdown-toggle dropdown-toggle-split m-0 p-0" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                              <span class="icon icon-sm">
                                  <span class="fas fa-ellipsis-h icon-dark"></span>
                              </span>
                              <span class="visually-hidden">Toggle Dropdown</span>
                          </button>
                          <div class="dropdown-menu py-0">
                              <a class="dropdown-item rounded-top" href="{% url 'youtube:download_file' song.1 %}"><span class="fas fa-save me-2"></span>Save to disk</a>
                              <a class="dropdown-item" href="#"><span class="fas fa-edit me-2"></span>Edit</a>
                              <a class="dropdown-item text-danger rounded-bottom" href="#"><span class="fas fa-trash-alt me-2"></span>Remove</a>
                          </div>
                      </div>
                  </td>
              </tr>
        {%  endfor %}

      </tbody>
  </table>
        <div class="card-footer px-3 border-0 d-flex flex-column flex-lg-row align-items-center justify-content-between">

            {% if songs.has_other_pages %}
            <ul class="pagination pagination-lg justify-content-center">
                {% if songs.number == 1 %}
                    <li class="disabled"><a class="page-link">⇤</a></li>
                {% else %}
                    <li><a class="page-link" href="?{% url_replace request 'page' 1 %}">⇤</a></li>
                {% endif %}
                {% if songs.has_previous %}
                    <li><a class="page-link" href="?{% url_replace request 'page' songs.previous_page_number %}">&laquo;</a></li>
                {% else %}
                    <li class="disabled"><a class="page-link">&laquo;</a></li>
                {% endif %}
                {% for i in songs.paginator|proper_paginate:songs.number %}
                    {% if songs.number == i %}
                        <!--<li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>-->
                        <li class="page-item active" aria-current="page"><a class="page-link">{{ i }}</a></li>
                    {% else %}
                        <li><a class="page-link" href="?{% url_replace request 'page' i %}">{{ i }}</a></li>
                    {% endif %}
                {% endfor %}
                {% if songs.has_next %}
                    <li><a class="page-link" href="?{% url_replace request 'page' songs.next_page_number %}">&raquo;</a></li>
                {% else %}
                    <li class="disabled"><a class="page-link">&raquo;</a></li>
                {% endif %}
                {% if songs.number == songs.paginator.num_pages %}
                    <li class="disabled"><a class="page-link">⇥</a></li>
                {% else %}
                    <li><a class="page-link" href="?{% url_replace request 'page' songs.paginator.num_pages %}">⇥</a></li>
                {% endif %}
            </ul>
        {% endif %}


          <div class="fw-normal small mt-4 mt-lg-0">
              Showing {{ songs.start_index }}-{{ songs.end_index }} of {{ songs.paginator.count }} songs
          </div>
      </div>
    </div>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}