apps/gcp/urls.py
from django.urls import path
from . import views

app_name = 'gcp'

urlpatterns = [
    path('text-to-speech/', views.text_to_speech, name='text_to_speech'),
    path("speech-to-text/<str:local_file_name>/", views.speech_to_text, name="speech_to_text"),
    path("voice-files/", views.voice_files, name="voice_files"),
    path("examine-voice-file/<str:name>", views.output_file, name="output_file"),
]

core/urls.py
# -*- encoding: utf-8 -*-
"""
Copyright (c) 2019 - present AppSeed.us
"""

from django.contrib import admin
from django.urls import path, include  # add this

urlpatterns = [
    path('admin/', admin.site.urls),                # Django admin route
    path('weather/', include('apps.weather.urls', namespace='weather')),
    path('mp3-extractor/', include('apps.youtube.urls', namespace='youtube')),
    path('gcp/', include('apps.gcp.urls', namespace='gcp')),
    path('aws/', include('apps.aws.urls', namespace='aws')),
    path('', include('apps.authentication.urls')),  # Auth routes - login / register
    path('', include('apps.home.urls')),             # UI Kits Html files
]

apps/gcp/views.py
import io
import glob
import mimetypes
import os

from django.conf import settings as project_settings
from django.http import HttpResponse
from django.shortcuts import render
from google.cloud import speech_v1p1beta1, texttospeech


def text_to_speech(request):
    """ Convert text from the form into MP3 file"""
    # Instantiates a client
    client = texttospeech.TextToSpeechClient()

    # Set the text input to be synthesized
    text_to_convert = request.GET.get("text_to_speech", "Witaj Arturze!")
    name_of_speech_file = request.GET.get("name_of_speech_file", "Witaj Arturze!")

    synthesis_input = texttospeech.SynthesisInput(text=text_to_convert)

    # Build the voice request, select the language code ("en-US") and the ssml
    # voice gender ("neutral")
    voice = texttospeech.VoiceSelectionParams(
        language_code="pl-PL", ssml_gender=texttospeech.SsmlVoiceGender.MALE
    )

    # Select the type of audio file you want returned
    audio_config = texttospeech.AudioConfig(
        audio_encoding=texttospeech.AudioEncoding.MP3
    )

    # Perform the text-to-speech request on the text input with the selected
    # voice parameters and audio file type
    response = client.synthesize_speech(
        input=synthesis_input, voice=voice, audio_config=audio_config
    )

    # The response's audio_content is binary.
    file_path = project_settings.MEDIA_ROOT
    with open(file_path + "/tts/" + name_of_speech_file + ".mp3", "wb") as out_file:
        # Write the response to the output file.
        out_file.write(response.audio_content)
        print(f"Audio content written to file {name_of_speech_file}.mp3")
    return render(request, 'gcp/text-to-speech.html')


def speech_to_text(request, local_file_name):
    """
    Transcribe a short audio file using synchronous speech recognition
    Args:
      local_file_name Name of local audio file, without extension, e.g. audio
    """

    client = speech_v1p1beta1.SpeechClient()

    # The language of the supplied audio
    language_code = "pl-PL"
    local_file_path = local_file_name + '.mp3'
    local_full_path = project_settings.MEDIA_ROOT + '/stt/' + local_file_path

    with io.open(local_full_path, "rb") as f:
        content = f.read()
    audio = {"content": content}

    config = speech_v1p1beta1.RecognitionConfig(
        encoding=speech_v1p1beta1.RecognitionConfig.AudioEncoding.MP3,
        sample_rate_hertz=16000,
        language_code=language_code,
    )

    # Detects speech in the audio file
    response = client.recognize(config=config, audio=audio)
    print(f"{response=}")

    for result in response.results:
        # First alternative is the most probable result
        alternative = result.alternatives[0]
        print(f"Transcript: {alternative.transcript}")
        print(f"Confidence: {alternative.confidence}")

    return render(
        request,
        "gcp/speech-to-text.html", {
            'local_file_name': local_file_name,
            'local_file_path': local_file_path,
            'transcript': alternative.transcript,
            'confidence': alternative.confidence
        }
    )


def voice_files(request):
    voice_files_list = []
    dir_path = project_settings.MEDIA_ROOT
    for full_path in glob.iglob(dir_path + '/stt/' + '*.mp3'):
        voice_files_list.append([os.path.basename(full_path), os.path.basename(full_path)[:-4]])
    return render(request, "gcp/voice-files.html", {'voice_files_list': voice_files_list})


def output_file(request, name):
    file_path = os.path.join(project_settings.MEDIA_ROOT) + "/stt/" + name + ".mp3"
    if os.path.exists(file_path):
        with open(file_path, "rb") as fh:
            mime_type, _ = mimetypes.guess_type(file_path)
            response = HttpResponse(fh.read(), content_type=mime_type)
            response["Content-Disposition"] = "inline; filename=" + os.path.basename(
                file_path
            )
            return response
    else:
        return render(request, "gcp/404.html")

apps/templates/gcp/speech-to-text.html
{% extends "layouts/base.html" %}

{% block title %} Weather {% endblock %}

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

    <div class="row">
      <div class="col-12 mb-4">
          <div class="card border-0 shadow components-section">
              <div class="card-body">
                  <div class="row mb-4 mb-lg-5">
                      <div class="col-12 col-md-12">
                          <h2 class="h5 mb-5">Speech-To-Text details (confidence = {{ confidence }})</h2>
                          <h2>{{ transcript }}</h2>
                      </div>
                  </div>

                  <!-- Title  -->
                  <div class="row">
                      <div class="col-md-4">
                          <div class="mt-6 mb-5">
                              <span class="h6">Original recording</span>
                          </div>
                      </div>
                  </div>
                  <!-- End of Title -->
                  <div class="row">
                      <audio controls>
                          <source
                                  src="{% url 'gcp:output_file' local_file_name %}"
                                  type="audio/mpeg">
                          Your browser does not support the audio element.
                      </audio>
                  </div>
              </div>
          </div>
      </div>
  </div>


{%  endblock content %}

apps/templates/gcp/text-to-speech.html
{% extends "layouts/base.html" %}

{% block title %} Weather {% endblock %}

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

    <div class="row">
        <div class="col-12 col-xl-12">
            <div class="card card-body border-0 shadow mb-4">
                <h2 class="h5 mb-4">Text-To-Speech conversion</h2>
                <form action="{%  url 'gcp:text_to_speech' %}">
                    <div class="row">
                        <div class="col-md-12 mb-3">
                            <div>
                                <label for="text_to_speech">Text to convert</label>
                                <textarea class="form-control mb-4"
                                        id="text_to_speech"
                                        name="text_to_speech"
                                        type="text"
                                        placeholder="Type your text to convert into speech ..."
                                        rows="6"
                                        required></textarea>

                                <label for="name_of_speech_file">Name of file</label>
                                <input
                                        class="form-control"
                                        id="name_of_speech_file"
                                        name="name_of_speech_file"
                                        type="text"
                                        placeholder="Give a name to your MP3 file with speech ..."
                                        required>
                            </div>
                        </div>
                    </div>
                    <div class="mt-3">
                        <button class="btn btn-gray-800 mt-2 animate-up-2" type="submit">Convert to speech </button>
                    </div>
                </form>
            </div>
        </div>
    </div>

{%  endblock content %}

apps/templates/gcp/voice-files.html
{% extends "layouts/base.html" %}

{% load proper_paginate %}
{% load url_replace %}

{% block title %} Voice files and recordings {% endblock %}

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

    <div class="card card-body border-0 shadow table-wrapper table-responsive">
        <h2 class="h5 mb-4">Voice files and recordings</h2>
        <table class="table table-hover">
            <thead>
              <tr>
                  <th class="border-gray-200">#</th>
                  <th class="border-gray-200">Title</th>
                  <th class="border-gray-200">Preview</th>
                  <th class="border-gray-200">Action</th>
              </tr>
          </thead>
            <tbody>
            {%  for vf in voice_files_list %}
              <!-- Item -->
              <tr>
                  <td>
                      <a href="#" class="fw-bold">
                          {{ forloop.counter }}
                      </a>
                  </td>
                  <td>
                      <span class="fw-normal">{{ vf.0 }}</span>
                  </td>
                  <td><span class="fw-normal">
                      <audio controls>
                          <source
                                  src="{% url 'gcp:output_file' vf.1 %}"
                                  type="audio/mpeg">
                          Your browser does not support the audio element.
                      </audio>
                  </span>
                  </td>
                  <td>
                      <a
                              class="btn btn-info"
                              href="{%  url 'gcp:speech_to_text' vf.1 %}" role="button"
                      >
                          Speech To Text
                      </a>
                  </td>
              </tr>
        {%  endfor %}

      </tbody>
        </table>
    </div>


{%  endblock content %}